const files=['channel_economics','competitor_price_history','competitor_prices_by_channel','customer_quotes','customer_survey','historical_sales_weekly','market_context','marketing_funnel_monthly','price_test_results','seasonality_and_weather'];
const S={};const n=x=>Number(x)||0,eur=x=>'€'+n(x).toFixed(2),pct=x=>n(x).toFixed(1)+'%',rows=p=>S.price_test_results.filter(x=>n(x.price_eur)===p),map={'DTC Online':'Paid Social','Retail/Grocery':'Retail Sampling','Gym & Office':'Influencer / Content'};
function csv(t){let [h,...ls]=t.trim().split(/\r?\n/).map(x=>x.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/));return ls.map(a=>Object.fromEntries(h.map((k,i)=>[k,(a[i]||'').replace(/^"|"$/g,'')])))}
const avg=(c,k)=>{let r=S.marketing_funnel_monthly.filter(x=>x.channel===map[c]);return r.reduce((a,x)=>a+n(x[k]),0)/Math.max(1,r.length)};
function accept(p){let a=[1.79,2.19,2.59],y=a.map(x=>n(rows(x)[0]?.estimated_acceptance_pct_of_survey)),i=a.findIndex(x=>x>=p);if(i<=0)return y[0];if(i<0)i=2;return y[i-1]+(y[i]-y[i-1])*(p-a[i-1])/(a[i]-a[i-1])}
function contrib(p,c){let a=[1.79,2.19,2.59],y=a.map(x=>n(rows(x).find(r=>r.channel===c)?.unit_contribution_eur)),i=a.findIndex(x=>x>=p);if(i<=0)return y[0];if(i<0)i=2;return y[i-1]+(y[i]-y[i-1])*(p-a[i-1])/(a[i]-a[i-1])}
const mix=mode=>mode==='Jonas'?{'DTC Online':.2,'Retail/Grocery':.25,'Gym & Office':.55}:{'DTC Online':.25,'Retail/Grocery':.55,'Gym & Office':.2};
const blend=(p,m)=>Object.entries(m).reduce((a,[c,w])=>a+w*contrib(p,c),0),pay=(p,m)=>Object.entries(m).reduce((a,[c,w])=>a+w*avg(c,'cac_eur')/Math.max(.01,contrib(p,c)),0),obj=(p,m)=>accept(p)*blend(p,m);
function load(){Promise.all(files.map(f=>fetch('./data/'+f+'.csv',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(f);return r.text()}).then(t=>[f,csv(t)]))).then(a=>{a.forEach(([k,v])=>S[k]=v);document.querySelector('#dataStatus').className='status ok';document.querySelector('#dataStatus').textContent='Data loaded: 12/12 exhibits · sourced rows are live from data/';render()}).catch(e=>{document.querySelector('#dataStatus').className='status error';document.querySelector('#dataStatus').textContent='Data could not load. Use Vercel or a local web server, not file://. '+e.message})}
function render(){evidence();rec();pricing();scenarios();channels();positioning();recon();cities();stake();market();sales();history();document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tabpane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')})}
function evidence(){let u=S.historical_sales_weekly.reduce((a,x)=>a+n(x.units_sold),0),sp=S.marketing_funnel_monthly.reduce((a,x)=>a+n(x.spend_eur),0),ac=S.marketing_funnel_monthly.reduce((a,x)=>a+n(x.conversions_customers_acquired),0);document.querySelector('#kpiUnits').textContent=(u/1e6).toFixed(2)+'m';document.querySelector('#kpiCAC').textContent=eur(sp/ac);document.querySelector('#priceChart').innerHTML='<div class="legend">● acceptance &nbsp; <i>●</i> contribution / unit</div><svg viewBox="0 0 520 210" role="img" aria-label="Observed price anchors">'+[1.79,2.19,2.59].map((p,i)=>{let x=100+i*160,a=accept(p),c=Math.max(...rows(p).map(r=>n(r.unit_contribution_eur)));return `<circle cx="${x}" cy="${180-a*2.2}" r="7" fill="#0b716b"/><circle cx="${x}" cy="${180-c*75}" r="7" fill="#e66d3f"/><text x="${x}" y="202" text-anchor="middle">€${p.toFixed(2)}</text><text x="${x}" y="${172-a*2.2}" text-anchor="middle">${a.toFixed(1)}%</text><text x="${x}" y="${172-c*75}" text-anchor="middle">€${c.toFixed(2)}</text>`}).join('')+'<text x="260" y="15" text-anchor="middle">Observed Exhibit 11 anchors</text></svg>'}
function rec(){document.querySelector('#recommendation').innerHTML='<h2>Recommendation: a measurable bridge</h2><p>The controls below show how the answer changes under Jonas’s premium ambition versus Elena’s payback discipline.</p><div class="rec"><div class="metric"><b>€2.19</b><small>bridge price <span class="badge sourced">EXH 11</span></small></div><div class="metric"><b>51.7%</b><small>observed acceptance <span class="badge sourced">EXH 11</span></small></div><div class="metric"><b>€0.89</b><small>blended contribution <span class="badge assumption">MODEL</span></small></div><div class="metric"><b>3:1</b><small>LTV:CAC target <span class="badge sourced">EXH 7</span></small></div></div><div class="trade"><b>Not optimized for:</b> maximum premium equity at €2.59 or minimum payback at the lowest price. This is the measurable compromise between Jonas and Elena.</div><button class="primary" id="memoBtn">Generate recommendation memo</button>';document.querySelector('#memoBtn').onclick=memo}
function pricing(){let parent=document.querySelector('#priceCards').parentElement,old=document.querySelector('#continuousControls');if(old)old.remove();let box=document.createElement('div');box.id='continuousControls';box.className='simulation';box.innerHTML='<span class="badge assumption">MODELED</span> Continuous demand curve <label>Price <input id="priceSlider" type="range" min="1.79" max="2.59" step=".01" value="2.19"><output id="priceValue">€2.19</output></label><p class="formula">Objective = interpolated acceptance (%) × blended contribution (€ / unit). Linear interpolation between the three observed Exhibit 11 anchors.</p><div id="liveMetrics" class="liveMetrics"></div><div id="uncertainty" class="uncertainty"></div>';parent.insertBefore(box,document.querySelector('#priceCards'));document.querySelector('#priceSlider').oninput=e=>live(n(e.target.value));live(2.19);document.querySelector('#priceCards').innerHTML=[1.79,2.19,2.59].map(p=>`<div class="pc ${p===2.19?'selected':''}"><span class="badge sourced">EXH 11</span><p><b>${eur(p)}</b></p><div>Acceptance <strong>${pct(accept(p))}</strong></div><div>Contribution range ${eur(Math.min(...rows(p).map(r=>n(r.unit_contribution_eur))))}–${eur(Math.max(...rows(p).map(r=>n(r.unit_contribution_eur))))}</div></div>`).join('')}
function live(p){let m=mix('Elena'),a=accept(p),c=blend(p,m),best=Array.from({length:81},(_,i)=>1.79+i*.01).reduce((b,x)=>obj(x,m)>obj(b,m)?x:b,1.79);document.querySelector('#priceValue').value=eur(p);document.querySelector('#liveMetrics').innerHTML=`<div><b>${eur(p)}</b><small>continuous price</small></div><div><b>${pct(a)}</b><small>interpolated acceptance</small></div><div><b>${eur(c)}</b><small>blended contribution</small></div><div><b>${eur(p*a/100)}</b><small>revenue / accepted unit</small></div>`;document.querySelector('#uncertainty').innerHTML=`<div class="rangebar"><i style="left:${(best-1.79)/.8*100}%"></i></div><b>Inspectable optimum: ${eur(best)}</b> under Elena’s current mix · ${obj(best,m).toFixed(1)} objective units <span class="badge assumption">MODEL</span>`}
function scenarios(){let j={p:2.59,m:mix('Jonas'),name:'Jonas'},e={p:2.19,m:mix('Elena'),name:'Elena'};for(const x of [j,e]){x.a=accept(x.p);x.c=blend(x.p,x.m);x.pay=pay(x.p,x.m)}document.querySelector('#scenarios').innerHTML='<div class="toggle"><button class="active" data-mode="compare">Compare</button><button data-mode="Jonas">Jonas</button><button data-mode="Elena">Elena</button></div><div id="scenarioContent"></div><p class="muted">Assumptions: Jonas mix = 20% DTC / 25% retail / 55% gym; Elena mix = 25% DTC / 55% retail / 20% gym. Uncertainty band = 0.8× to 1.25× base payback.</p>';const show=mode=>document.querySelector('#scenarioContent').innerHTML='<div class="scenarioGrid">'+[j,e].filter(x=>mode==='compare'||x.name===mode).map(x=>`<div class="scenario ${x.name==='Jonas'?'jonas':''}"><h3>${x.name==='Jonas'?'Jonas’s priorities':'Elena’s priorities'}</h3><div class="scenarioPrice">${eur(x.p)}</div><p>${pct(x.a)} acceptance · ${eur(x.c)} contribution / unit</p><p><b>${x.pay.toFixed(1)} months</b> base payback</p><div class="band"><i style="width:${Math.min(100,x.pay/60*100)}%"></i></div><small>Best ${(x.pay*.8).toFixed(1)} · worst ${(x.pay*1.25).toFixed(1)} months</small></div>`).join('')+'</div>';document.querySelectorAll('.toggle button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');show(b.dataset.mode)});show('compare')}
function channels(){let ch=[...new Set(S.price_test_results.map(x=>x.channel))];document.querySelector('#channelTable').innerHTML='<table><tr><th>Channel</th><th>Net / unit</th><th>Avg CAC</th><th>Avg LTV</th><th>Payback</th></tr>'+ch.map(c=>{let r=S.channel_economics.find(x=>x.channel===c&&n(x.illustrative_retail_price_eur)===2.19),p=avg(c,'cac_eur')/contrib(2.19,c);return `<tr><td>${c}</td><td>${eur(r?.net_price_to_lumen_eur)} <span class="badge sourced">EXH 9</span></td><td>${eur(avg(c,'cac_eur'))}</td><td>${eur(avg(c,'ltv_estimate_eur'))}</td><td>${p.toFixed(1)} mo</td></tr>`}).join('')+'</table>'}
function positioning(){let d=S.competitor_prices_by_channel,cs=[...new Set(d.map(x=>x.competitor))],lo=.8,hi=3.3,x=p=>28+(p-lo)/(hi-lo)*68;document.querySelector('#positioning').innerHTML=cs.map(c=>{let r=d.filter(x=>x.competitor===c),a=Math.min(...r.map(x=>n(x.price_eur))),b=Math.max(...r.map(x=>n(x.price_eur)));return `<div class="dot" style="left:${x((a+b)/2)}%;top:${c==='PulsUp'?84:c==='Mate Libre'?66:c==='VoltFit'?28:48}%"><span></span>${c}<small>${eur(a)}–${eur(b)}</small></div>`}).join('')+[1.79,2.19,2.59].map((p,i)=>`<div class="dot lumen" style="left:${x(p)}%;top:${12+i*22}%"><span></span>LUMEN ${eur(p)}</div>`).join('')+`<div class="axis"></div><span class="axislabel" style="left:7%">€0.80</span><span class="axislabel" style="right:2%">€3.30</span>`}
function recon(){let s=S.customer_survey,q=S.customer_quotes,segs=[...new Set(s.map(x=>x.segment))];document.querySelector('#reconcile').innerHTML='<div class="paired">'+segs.map(g=>{let r=s.filter(x=>x.segment===g),hi=r.filter(x=>n(x.price_sensitivity_1_10)>=7).length/r.length,quote=q.find(x=>x.segment===g)?.quote||'No quote supplied';return `<div class="pair"><h3>${g}</h3><div><span class="badge sourced">SURVEY n=${r.length}</span> ${pct(hi*100)} high price sensitivity (7–10 / 10)</div><div><span class="badge hypothesis">QUOTE</span> “${quote}”</div><p class="warn">Potential disagreement: the survey quantifies price sensitivity; the quote foregrounds the reason for purchase rather than a ranked driver.</p></div>`}).join('')+'</div>'}
function cities(){let r=S.market_context.filter(x=>x.dimension_type==='region'&&x.metric==='population_share_of_market'&&x.name!=='Other Germany'),peak=Math.max(...S.seasonality_and_weather.map(x=>n(x.seasonality_index_100_avg)));r.sort((a,b)=>n(b.value)-n(a.value));document.querySelector('#city').innerHTML='<div class="cityrank">'+r.slice(0,4).map((x,i)=>`<div><b>${i+1}. ${x.name}</b><span>${pct(n(x.value)*100)} named market share</span><div class="bar"><i style="width:${n(x.value)/n(r[0].value)*100}%"></i></div><small>Composite = share × peak seasonality (${peak}/100). <span class="badge assumption">MODEL</span></small></div>`).join('')+'</div><p class="muted">Exhibit 1 provides illustrative regional shares, not observed German demand. Other Germany is not a city candidate.</p>'}
function stake(){let e=S.channel_economics.filter(x=>n(x.illustrative_retail_price_eur)===2.19),u=S.historical_sales_weekly.reduce((a,x)=>a+n(x.units_sold),0),sp=S.marketing_funnel_monthly.reduce((a,x)=>a+n(x.spend_eur),0),ac=S.marketing_funnel_monthly.reduce((a,x)=>a+n(x.conversions_customers_acquired),0);document.querySelector('#stakeholders').innerHTML=`<div class="stake"><h3>Retail / distribution</h3><span class="badge sourced">EXHIBIT-BACKED</span><p>At €2.19, net/unit is ${e.map(x=>x.channel+' '+eur(x.net_price_to_lumen_eur)).join(', ')}. Exhibit 6 shows ${(u/1e6).toFixed(2)}m home-market units.</p></div><div class="stake"><h3>Investors</h3><span class="badge sourced">EXHIBIT-BACKED</span><p>€9.1bn market context, ~7% CAGR, ~35% European share, and observed CAC ${eur(sp/ac)}.</p></div><div class="stake"><h3>Government / public sector</h3><span class="badge hypothesis">HYPOTHESIS</span><p>Low-sugar / natural-caffeine positioning may intersect with public priorities. Not a regulatory or grant-readiness claim; legal and labelling diligence remains open.</p></div>`}
function market(){document.querySelector('#market').innerHTML='<div class="rec"><div class="metric"><b>€9.1bn</b><small>2026 context <span class="badge sourced">EXH 1</span></small></div><div class="metric"><b>~7%</b><small>category CAGR <span class="badge sourced">BRIEF</span></small></div><div class="metric"><b>~35%</b><small>European share <span class="badge sourced">BRIEF</span></small></div></div>'}
function sales(){let u=S.historical_sales_weekly.reduce((a,x)=>a+n(x.units_sold),0),r=S.historical_sales_weekly.reduce((a,x)=>a+n(x.revenue_eur),0);document.querySelector('#sales').innerHTML=`<div class="rec"><div class="metric"><b>${(u/1e6).toFixed(2)}m</b><small>units <span class="badge sourced">EXH 6</span></small></div><div class="metric"><b>${eur(r/1e6)}m</b><small>revenue <span class="badge sourced">EXH 6</span></small></div></div>`}
function history(){let h=S.competitor_price_history,a={};h.forEach(x=>(a[x.competitor]??=[]).push(n(x.shelf_price_eur)));document.querySelector('#history').innerHTML='<table><tr><th>Competitor</th><th>12-mo avg</th><th>Promo months</th></tr>'+Object.entries(a).map(([c,v])=>`<tr><td>${c}</td><td>${eur(v.reduce((a,b)=>a+b,0)/v.length)}</td><td>${h.filter(x=>x.competitor===c&&x.promo_active==='True').length}</td></tr>`).join('')+'</table>'}
function memo(){let p=n(document.querySelector('#priceSlider').value),m=mix('Elena'),j=pay(2.59,mix('Jonas')),e=pay(2.19,mix('Elena')),w=window.open();w.document.write(`<html><head><title>LUMEN memo</title><style>body{font:14px Arial;max-width:760px;margin:45px auto;color:#17242b}h1{font:28px Georgia}.box{background:#eef6f1;padding:14px;margin:14px 0}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><h1>LUMEN Germany market-entry memo</h1><p>Generated from current dashboard state · observed Exhibits 1–12 plus labeled modeling assumptions.</p><div class="box"><b>Current continuous price:</b> ${eur(p)}<br><b>Interpolated acceptance:</b> ${pct(accept(p))}<br><b>Elena-mix contribution:</b> ${eur(blend(p,m))} / unit</div><h2>CMO versus CFO</h2><table><tr><th></th><th>Jonas</th><th>Elena</th></tr><tr><td>Price</td><td>€2.59</td><td>€2.19</td></tr><tr><td>Payback band</td><td>${(j*.8).toFixed(1)}–${(j*1.25).toFixed(1)} months</td><td>${(e*.8).toFixed(1)}–${(e*1.25).toFixed(1)} months</td></tr></table><h2>Decision</h2><p>Use €2.19 as a bridge launch price with mixed retail and gym channels.</p><p><b>Deliberately not optimized for:</b> maximum premium equity at €2.59 or minimum payback at the lowest price.</p><script>window.print()</script></body></html>`);w.document.close()}
load();

const chatAnswers=[
 {keys:['prezzo','costa','€2.19','2.19','recommended price','price'],answer:'The current recommendation is €2.19: estimated acceptance is 51.7% and contribution is €0.63–€1.16 per unit. It is the compromise between €1.79 (higher acceptance, thinner margin) and €2.59 (higher margin, acceptance nearly halves). Source: Exhibit 11.'},
 {keys:['canale','dtc','retail','grocery','gym','office','best channel','channel'],answer:'The plan suggests Retail/Grocery and Gym & Office as initial channels, using DTC Online to learn and retarget. The displayed mix is 20% DTC, 50% Retail/Grocery and 30% Gym & Office. This is an assumption to validate, not a forecast.'},
 {keys:['competitor','concorrente','pulsup','mate libre','voltfit','root'],answer:'PulsUp is mass market (€0.96–€1.28), Mate Libre is heritage (€1.37–€1.83), VoltFit is premium (€2.10–€2.72), and Root & Rise is boutique (€2.54–€3.11). At €2.19, LUMEN enters premium territory without choosing the highest price. Source: Exhibit 2.'},
 {keys:['cac','ltv','payback','roi','margine','contributo','investimento'],answer:'CAC is the cost to acquire a customer, LTV is the estimated customer value, and payback is the modeled time to recover CAC. Observed blended CAC is about €44 and the target LTV:CAC is 3:1. These are simulations, not German sales. Sources: Exhibits 7, 9 and 11.'},
 {keys:['berlin','città','citta','regione','quando','lancio','mese','stagion'],answer:'Berlin is the model priority because it has the largest named regional share: 18% of the 2026 market context. The highest seasonality readings are in June, July and August, so the plan suggests a late-spring or early-summer activation. These are not German sales data.'},
 {keys:['cliente','segmento','sondaggio','survey','studente','profession'],answer:'The survey includes about 420 German respondents with segment, spend, price sensitivity, preferred channel and purchase intent. Retail/Grocery is the most selected preferred channel (46.4%). The chatbot does not use or display names, emails or respondent IDs.'},
 {keys:['risch','risk','limite','manc','tedesc','german','main risks'],answer:'The main limitation is that LUMEN has no German sales yet. Historical sales come from the Netherlands, Denmark and Sweden; market estimates and price tests are indirect evidence. The recommendation should therefore be validated with a pilot launch.'},
 {keys:['market size','mercato','9.1','cagr','growth','crescita'],answer:'The German functional-beverage market context is estimated at €9.1bn in 2026, with approximately 7% CAGR through 2033 and about 35% of European category value. This is total market opportunity sizing, not a LUMEN revenue forecast. Source: Exhibit 1 and the case brief.'},
 {keys:['cost','costi','ingredient','production','logistics'],answer:'The cost breakdown covers ingredients, production, packaging, logistics and other per-unit components. Ingredients include green-tea caffeine and adaptogens. Use Exhibit 8 to understand the current blended gross margin; it describes home-market economics, not guaranteed German costs.'},
 {keys:['promotion','promo','discount','sconto'],answer:'Promotional pressure matters, especially for price-sensitive customers. The qualitative data includes customers who would buy during a promotion but consider the product a stretch at full price. A controlled offer around €2.19 is safer than permanently lowering the shelf price.'},
 {keys:['student','students','budget'],answer:'Students & Budget-Conscious respondents show the strongest price sensitivity in the dashboard. Their quotes suggest that promotions can trigger trial. For this segment, test targeted offers without making the permanent list price look mass-market.'},
 {keys:['fitness','gym-goer','performance','voltfit'],answer:'Fitness & Gym-Goers are less price-sensitive than students and respond to performance and taste. A Gym & Office launch channel can reach this segment, while the product claim should remain evidence-based and compliant.'},
 {keys:['professional','wellness','clean label','clean ingredients'],answer:'Urban Wellness Professionals show low measured price sensitivity and a willingness to pay more for clean ingredients. They support a premium positioning hypothesis, but the evidence is survey-based and should be validated through German sell-through.'},
 {keys:['commuter','kiosk','station','on-the-go'],answer:'On-the-go Commuters value convenience and availability. Their quote suggests that being present at kiosks or near stations may be more important than adding another digital feature. This supports testing convenient retail points of sale.'},
 {keys:['seasonality','weather','temperature','summer'],answer:'The seasonality data shows the strongest supplied readings in June, July and August, with average temperatures around 18–19°C. This supports a late-spring or early-summer activation, but it is a planning signal rather than proof of German demand.'},
 {keys:['historical sales','home market','netherlands','denmark','sweden'],answer:'Historical sales cover 78 weeks in the Netherlands, Denmark and Sweden. They demonstrate existing operating experience and repeat-purchase potential, but they cannot be treated as German sales or copied directly into a German forecast.'},
 {keys:['data personal','privacy','email','identifier','personal data'],answer:'The customer survey contains name, email and respondent-ID fields, but the dashboard does not use them in the interface. The chatbot only returns aggregated findings and must never expose personal identifiers.'},
 {keys:['how use','how does','come funziona','work','chatbot'],answer:'Ask a question in the box or use a suggested question. The chatbot matches topic keywords to evidence-based answers about the LUMEN case. It is a local rules-based prototype, not an AI model, so it may ask you to rephrase an unrelated question.'},
 {keys:['ceo recommendation','final decision','what should we do','decision'],answer:'The recommended CEO decision is to enter Germany with a controlled pilot at €2.19, led by Retail/Grocery and Gym & Office, while using DTC to learn. This balances premium positioning with financial discipline; it is not a full-scale national rollout recommendation.'},
 {keys:['why germany','why enter','strategic rationale','opportunity'],answer:'Germany is strategically attractive because the 2026 functional-beverage market context is estimated at €9.1bn, around 35% of European category value, with approximately 7% category CAGR. The opportunity is large, but LUMEN still needs to validate local demand.'},
 {keys:['biggest risk','key risk','risk to the business','risks to the business'],answer:'The biggest business risk is extrapolating home-market performance to Germany without German sales evidence. Other risks include price sensitivity, promotional pressure, channel economics, regulatory diligence and slower-than-modeled payback.'},
 {keys:['competitive advantage','advantage','why lumen','differentiate'],answer:'LUMEN can differentiate through low sugar, natural caffeine from green tea, functional positioning and existing repeat-purchase experience in the Netherlands, Denmark and Sweden. These are positioning advantages, not guaranteed German competitive advantages.'},
 {keys:['investment','budget','spend','funding'],answer:'The current case does not provide a complete Germany launch budget. It provides CAC, LTV, channel economics and scenario assumptions to compare discipline and payback. A CEO should approve a staged pilot budget with explicit stop/go metrics rather than infer a full investment from the €9.1bn market size.'},
 {keys:['success metric','kpi','measure success','pilot success'],answer:'A sensible pilot scorecard should track sell-through by channel, repeat purchase, acceptance at €2.19, CAC, contribution per unit, payback, promotional dependency and retailer reorder signals. The case provides starting benchmarks, but Germany-specific targets should be agreed before launch.'},
 {keys:['scale','scaling','national rollout','expand'],answer:'Scale only after the pilot validates demand and unit economics. The decision gates should include repeat purchase, channel-level contribution, CAC stability, retailer reorder and evidence that demand is not dependent on heavy discounting.'},
 {keys:['not optimize','trade off','trade-off','sacrifice'],answer:'Choosing €2.19 deliberately avoids optimizing for maximum premium brand equity at €2.59 and minimum acceptance at €1.79. The strategy prioritizes a measurable bridge between brand ambition and financial discipline.'},
 {keys:['cfo decision','financial recommendation','finance recommendation'],answer:'The CFO-facing recommendation is to approve a staged pilot at €2.19, with a controlled budget and channel-level stop/go gates. Do not treat the €9.1bn market context as a sales forecast or commit to a national rollout before German unit economics are observed.'},
 {keys:['cash runway','runway','cash'],answer:'The case does not provide LUMEN’s total cash balance or a complete Germany launch budget, so runway cannot be calculated responsibly. The available evidence supports comparing CAC, contribution and modeled payback, not claiming a cash forecast.'},
 {keys:['gross margin','margin percentage','margin'],answer:'Current blended gross margin in the home markets is approximately 30% in Exhibit 8. Germany contribution must also account for channel deductions and fulfillment, so the CFO should use channel-level contribution rather than retail shelf price alone.'},
 {keys:['lowest cac','cheapest acquisition','efficient channel'],answer:'Gym & Office has the lowest observed average CAC among the displayed channels at about €37.32, followed by DTC Online at €45.55 and Retail/Grocery at €60.63. CAC alone is not enough: contribution, reach and repeat purchase must be considered together.'},
 {keys:['fastest payback','quickest payback','pay back fastest'],answer:'In the current model, Gym & Office has the fastest channel payback at about 33.0 months, while DTC Online is about 39.3 months and Retail/Grocery about 96.2 months. These are modeled comparisons based on home-market funnel economics, not German results.'},
 {keys:['break even','break-even','breakeven','profitability'],answer:'The dashboard does not calculate a complete company break-even point because it lacks fixed costs, launch budget and German volume assumptions. It does provide contribution per unit and payback comparisons that can support a later break-even model.'},
 {keys:['sensitivity','downside','worst case','stress test'],answer:'The current downside view is an uncertainty band around modeled payback, using 0.8× to 1.25× the base estimate. A stronger CFO stress test should vary price acceptance, CAC, contribution, repeat purchase and promotional dependency before approving scale.'},
 {keys:['stop go','stop/go','go no-go','gates'],answer:'Recommended go/no-go gates are: stable CAC, positive channel contribution, repeat purchase, retailer reorder intent, acceptable price acceptance at €2.19 and limited reliance on discounts. If these are not met, pause scale and revise the channel or price mix.'}
 ,{keys:['cmo decision','brand recommendation','marketing recommendation'],answer:'The CMO-facing recommendation is to protect a premium-but-accessible position at €2.19, supported by low sugar, natural caffeine and functional credentials. Use Gym & Office and selected Retail/Grocery placements to build credibility, while testing the message before scaling brand spend.'},
 {keys:['premium','premium positioning','brand equity'],answer:'€2.59 would maximize premium signaling and contribution per unit, but estimated acceptance falls to 26.7%. €2.19 is a bridge: it sits near VoltFit’s price territory while keeping more accessible demand. The trade-off is less maximum premium equity in exchange for a broader launch base.'},
 {keys:['brand message','messaging','communication','campaign'],answer:'The strongest message territory is a low-sugar, sparkling functional drink with natural caffeine from green tea and a light adaptogen blend. Treat performance, health and clean-label language carefully: claims need evidence and regulatory review before external use.'},
 {keys:['differentiate','differentiation','position'],answer:'Position LUMEN between accessible premium performance and clean-label wellness. Avoid competing only on low price against PulsUp; instead combine taste, function, natural caffeine and credible repeat-purchase experience from the existing markets.'},
 {keys:['target audience','target segment','audience','who target'],answer:'Prioritize Urban Wellness Professionals and Fitness & Gym-Goers for premium willingness and functional relevance. Use Students & Budget-Conscious customers selectively with controlled promotions, and test convenient points of sale for On-the-go Commuters.'},
 {keys:['awareness','brand awareness','known'],answer:'The survey measures awareness of PulsUp, Mate Libre, VoltFit and Root & Rise, but LUMEN has not yet generated German sales evidence. Awareness should therefore be treated as a launch objective to measure, not as an established German brand asset.'},
 {keys:['discount','discounting','promotion strategy','promo strategy'],answer:'Use promotions as a controlled trial and learning mechanism, not as the core brand promise. Student quotes show promotional interest, while professionals may accept a higher price for clean ingredients. Permanent discounting could weaken the premium position.'},
 {keys:['launch story','story','narrative','why buy'],answer:'The launch story should connect everyday energy with functional, low-sugar and natural ingredients. Make the benefit easy to understand, then support it with taste and performance proof. The case does not justify unsupported health or regulatory claims.'},
 {keys:['creative','content','influencer','social media'],answer:'Content should demonstrate the product in real use: workdays, commuting, training and study periods. Influencer or content activity can support Gym & Office and DTC learning, but performance should be judged by quality of engagement, conversion and repeat purchase—not reach alone.'}
];
function chatReply(question){const q=question.toLowerCase();const hit=chatAnswers.find(x=>x.keys.some(k=>q.includes(k)));return hit?hit.answer:'I can answer questions about pricing, channels, competitors, CAC/LTV/payback, customers, Berlin, seasonality and data limitations. Try rephrasing your question around one of these topics.'}
function addChatMessage(text,kind){const box=document.querySelector('#chatMessages'),el=document.createElement('div');el.className='chat-message '+kind;el.textContent=text;box.appendChild(el);box.scrollTop=box.scrollHeight}
function askChat(question){const clean=question.trim();if(!clean)return;addChatMessage(clean,'user');addChatMessage(chatReply(clean),'bot')}
document.querySelectorAll('.chat-suggestions button').forEach(b=>b.onclick=()=>askChat(b.dataset.question));
document.querySelector('#chatForm').onsubmit=e=>{e.preventDefault();const input=document.querySelector('#chatInput');askChat(input.value);input.value='';input.focus()};
